[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "cmaas_utils"
version = "0.1.0"
authors = [
  { name="Albert Bode", email="abode@illinois.edu" },
]
description = "A package containing the core utility functions for the cmaas effort"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = ""
Issues = ""